#########
## Authoer: Kabir Bolatito
##
## Usage:
##    Deploy Command: $(which ansible-playbook) playbook.yml -i ec2.py -l "tag_Name_deployer" -u ubuntu
##    Delete Deploy Command: $(which ansible-playbook) playbook.yml -i ec2.py -l "tag_Name_deployer" -u ubuntu -e action=delete
##
## Using tag_Name_deployer as oppose to the general host list maintenance is ideal as we can dynamically target the specific instance
## tag_Name_deployer - this represent the Name = deloyer tag in my aws ec2
##
## To learn more about dynamic inventory: https://docs.ansible.com/ansible/latest/user_guide/intro_dynamic_inventory.html
###########
- name: Deploy Weather App
  hosts: all
  vars:
    - action: "deploy"
  tasks:
    - name: Copy Kubernetes Deploy File 
      copy:
        src: "k8s-deploy.yml"
        dest: ~/k8s-deploy.yml
        backup: yes
      become: yes
      become_user: root

    - name: Deploy Weather App
      command: kubectl apply -f ~/k8s-deploy.yml
      register: deploy
      when: action == "deploy"
    - debug: var=deploy
      when: action == "deploy"

    - name: Delete weather App Deployment
      command: kubectl delete -f ~/k8s-deploy.yml
      register: delete
      when: action == "delete"

    - debug: var=delete
      when: action == "delete"

    - name: Get Deployment State
      command: kubectl get deployments
      register: deployment
    - debug: var=deployment

    - name: Get Services State
      command: kubectl get svc
      register: services
    - debug: var=services