###################
## Author: Kabir Bolatito
## Description: Deploy ssh key. create ops_dba group and set the group to /etc/security/access.conf and /etc/sudoers
## This ansible deployments follows a dynamic inventory convention
##
## Usage:
##    $(which ansible-playbook) ansible/roles/jobs/tasks/ssh-key-deploy.yml -i ansible/ec2.py -l "tag_App_ssh" -f 5 -u ubuntu -e ec2_access_key=<aws key> -e ec2_secret_key=<aws secret key>
##
## Assuming the name of the instance have the tag App=ssh, wihtout maintaining a host list, we can dynamically target and deploy the ssh keys to those instance
##
#########
- name: Deploy SSH Keys
  hosts: all
  vars:
    - copy_local_key: 
        - "ssh-rsa BBBBB3NzaC1yc2EAAAADAQABAAABAQDDzCcIjvzZpGZakA5gZtIcxE1y6ekmtHxH77uNBEfhxWlKhfHDFhK45bPZ9Vlf+JhMutdMMNb4cOrhLncPY4NOjmlH9cv06vaBIlrMclrlET7wGjEQ+yskht41bggPi8+4DzrWKpbJXOpmgAiUdOPl3ix7jmpjuiBy6zke0vZ4mEclRaPP2qRelOd1KJABJwuiYhwG0P58CTZsD3s58jnljDDZi8hd9JVX621+WfzhoV8nPPsUfcKRaw70mOXGGibm1jkS9U0wbM7cWVZ8BjjS0vgMJfQZaxvME5CjIeqttW///SWkS/fHg23UY9yBe/3vchO7KW+OTF1nJmIOB0aR summit@Lexis-MacNow-Pre.staging"
    - create_user: ubuntu

  tasks:
    # SSH Key Deploy
    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ item }}"
      with_items:
        - "{{ copy_local_key }}"

    # Create ops_dba group and make sure it exist
    - name: Make sure we have a 'ops_dba' group
      group:
        name: ops_dba
        state: present
      become: yes
      become_user: root

    - name: Set group name
      file:
        path: "{{ item }}"
        group: ops_dba
      become: yes
      become_user: root
      with_items:
        - /etc/security/access.conf
        - /etc/sudoers