#########################################################################################################
## Author: Kabir Bolatito
## Email: tbola45@gmail.com
## Usage: 
##    Manual Trigger:  
##           curl -H "Accept: application/vnd.github.everest-preview+json" \
##           -H "Authorization: token <GITHUB_TOKEN>" \
##           --request POST \
##           --data '{"event_type": "trigger-build", "client_payload" :{ "action": "build"}}' \
##           https://api.github.com/repos/iamtito/weatherApp/dispatches
##
##    If GITHUB_TOKEN is in AWS SECRET MANAGER, Use $(aws secretsmanager get-secret-value --secret-id <secretName> | jq -r '.SecretString' | jq -r '<secretKeyValue>')
#########################################################################################################
name: Docker Build & Push
on: 
  push:
    branches:
      - master
    # paths-ignore:
    #   - '.github/**'
      
  #Below triggers this workflow, usage is in the above description
  repository_dispatch:
    types: trigger-build

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the weatherApp Docker Image
      run: |
        set -exv
        echo "REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }}" > .env
        docker build -t tbola45/weatherapp:latest .

    - name: Push weatherApp Image to Dockerhub
      run: |
        set -exv
        docker push tbola45/weatherapp:latest
